# Generated by Django 4.2.7 on 2023-12-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ctid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ctname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpname', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('ctid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.country')),
            ],
        ),
    ]
